// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVsoSEz5CYOOgPjLxufO7WcP2xP5U5-Hg',
    appId: '1:410035160431:web:2d4ab10729db6e1d13549a',
    messagingSenderId: '410035160431',
    projectId: 'me-a9ec5',
    authDomain: 'me-a9ec5.firebaseapp.com',
    storageBucket: 'me-a9ec5.firebasestorage.app',
    measurementId: 'G-5CR5YGWLTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QC9YL2bB70DfNJ3m9f4O44L_VaCEJOQ',
    appId: '1:410035160431:android:4581a9a69436278713549a',
    messagingSenderId: '410035160431',
    projectId: 'me-a9ec5',
    storageBucket: 'me-a9ec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFxtbkj0B2J9B3fx48YW218mtK0DYky4',
    appId: '1:410035160431:ios:d8a330898f2b469413549a',
    messagingSenderId: '410035160431',
    projectId: 'me-a9ec5',
    storageBucket: 'me-a9ec5.firebasestorage.app',
    iosBundleId: 'com.sit.secureMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFxtbkj0B2J9B3fx48YW218mtK0DYky4',
    appId: '1:410035160431:ios:6a77a0a68c107e9d13549a',
    messagingSenderId: '410035160431',
    projectId: 'me-a9ec5',
    storageBucket: 'me-a9ec5.firebasestorage.app',
    iosBundleId: 'com.example.secureMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVsoSEz5CYOOgPjLxufO7WcP2xP5U5-Hg',
    appId: '1:410035160431:web:97060f441f0fb83313549a',
    messagingSenderId: '410035160431',
    projectId: 'me-a9ec5',
    authDomain: 'me-a9ec5.firebaseapp.com',
    storageBucket: 'me-a9ec5.firebasestorage.app',
    measurementId: 'G-ZWS9F8E9B0',
  );
}
